### ISSUE TITLE
I found a few typos

### ISSUE THREAD

**Issue by egeesin** [yantis/instant-archlinux-on-mac#14]
While I was reading shell scripts I found a few typos in your code:

https://github.com/yantis/instant-archlinux-on-mac/blob/master/initial_configuration.sh#L79
`sytemctl`

Less crucial one:
https://github.com/yantis/instant-archlinux-on-mac/blob/master/mac-install.sh#L115
`Homerbrew`

**Comment by yantis** [comment]
Thank you! I went ahead and fixed these.
