### ISSUE TITLE
unsquashfs error?

### ISSUE THREAD

**Issue by chrisetheridge** [yantis/instant-archlinux-on-mac#2]
`2016-02-06 13:49:05 (610 MB/s) - '/root/initial_configuration.sh' saved [3290/3290]`

`Can't find a SQUASHFS superblock on /root/airootfs.sfs`
`Stopping "docker-vm"...`
`Machine "docker-vm" was stopped.`
`Remove our physical harddrive from the boot2docker virtualmachine`

**Comment by yantis** [comment]
should be fixed

**Comment by chrisetheridge** [comment]
I am still reaching this problem :/
