### ISSUE TITLE
Can't get it running on Sierra

### ISSUE THREAD

**Issue by dab** [yantis/instant-archlinux-on-mac#3]
Hello there, i got this message while running the script:

``` sh
/dev/disk2              GUID_partition_scheme
/dev/disk2s1            Apple_HFS                       /Volumes/ParagonFS.localized
installer: Cannot install on volume / because it is disabled.
installer: The version of macOS is too new.
```

What I can do to get it running?
Thanks!

**Comment by dab** [comment]
Found a problem — https://github.com/yantis/instant-archlinux-on-mac/pull/4

**Comment by yantis** [comment]
ParagonFS might not have been updated yet to work with Sierra.
