### ISSUE TITLE
Can't boot after installation. ERROR: fsck failed

### ISSUE THREAD

**Issue by dab** [yantis/instant-archlinux-on-mac#5]
Hello there,
Trying to get in working on my MacBook Pro 13”,
It’s installed fine, without errors, but after rebooting I got error:

```
fsck error 2 (no such file or directory) while executing fsck.ext4 
ERROR: fsck failed on /dev/sda4
Mount unknown filesystem type ‘ext4’
```

Any ideas how to solve this?
Thanks!

**Comment by yantis** [comment]
Can you please post more of your log?
