### ISSUE TITLE
2016.10.01/arch/x86_64/airootfs.sfs is no longer available 

### ISSUE THREAD

**Issue by Cthompson281** [yantis/instant-archlinux-on-mac#8]
I have tried installing arch on my 2015 MacBook Pro with a few errors. I had to change directory of the Paragon installer due to a name change i'm assuming. For me on 10.12.3 it is "/Volumes/ParagonFS.localized/FSInstaller.app/Contents/Resources/Paragon\ ExtFS\ for\ Mac.pkg -target /". So I got passed that and now the airootfs.sfs is no longer available and I have tried using others but they throw errors like this "pacman: error while loading shared libraries: libarchive.so.13: wrong ELF class: ELFCLASS64". Any help in what I could fix would be great! Thanks again for this repo, I am enjoying it but will love it more when arch is fully installed XD.

**Comment by yantis** [comment]
Fixed

**Comment by yantis** [comment]
I updated it to the latest SFS image though the other issues still exist.

**Comment by Cthompson281** [comment]
Any ideas as what it could be? I thought when I first pulled my own SFS image I grabbed the i686 but nope. Thanks again for looking into it.

**Comment by yantis** [comment]
It should work now. I updated to the latest SFS image as well as fixed the ParagonFS file location.

**Comment by Cthompson281** [comment]
Ok, I tried again and this is the new error

:: The following packages cannot be upgraded due to unresolvable dependencies:
      dkms  gcc

:: Do you want to skip the above packages for this upgrade? [y/N]
error: failed to prepare transaction (could not satisfy dependencies)
:: gcc: requires gcc-libs=6.2.1-1
:: dkms: requires gcc
:: gcc: requires gcc-libs=6.2.1-1
Stopping "docker-vm"...
Machine "docker-vm" was stopped.
Remove our physical harddrive from the boot2docker virtualmachine
VBoxManage: error: No storage device attached to device slot 0 on port 2 of controller 'SATA'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 393 of file VBoxManageStorageController.cpp

**Comment by Cthompson281** [comment]
Did they update the version of gcc-libs to > 6.2.1-1? It seems like it and gcc is and dkms are both dependent of that specific version it seems.

**Comment by yantis** [comment]
Thanks. Looks like I am going to have to redo the base docker images.

**Comment by Cthompson281** [comment]
I'd try to help but have 0 knowledge with Docker. Sorry :/

**Comment by yantis** [comment]
I fixed the base images.  I *think* it should work. Going to go ahead and do a fresh install on my Macbook.

**Comment by yantis** [comment]
Fresh install worked.

**Comment by Cthompson281** [comment]
It installed everything with no errors and when I tried to boot it gave me mount unknown filesystem type ext4 which I thought was odd so I tried going to the reFind menu hit F2 and tried booting to run the mkinitcpio -p linux command but it did the same thing and gets hung up. Do you think it's a hardware issue?

**Comment by yantis** [comment]
Can you please try the fallback options with F2?

**Comment by Cthompson281** [comment]
How do you do that? All I see if Graphical Interface Normal with/without microkernel updates.

**Comment by Cthompson281** [comment]
Never mind so I went into the file and changed the argument to the fallback img. I really do appreciate the help!

**Comment by yantis** [comment]
Awesome. Hopefully it works well now for you.

**Comment by Cthompson281** [comment]
Yeah it's booting only problem is no wifi. I'll look into that.

**Comment by yantis** [comment]
Fantastic.  Great to hear.
